# from rse_workbench.platform_contract import Installable
# from rse_workbench.platform_contract import compose_platform_recipe


from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

@dataclass
class Installable:
    """A tool installed into the platform image."""

    name: str
    kind: str
    commands: list[str]
    path: Optional[str] = None
    test: list[str] = field(default_factory=list)

    def install_lines(self) -> list[str]:
        return self.commands

    def test_lines(self) -> list[str]:
        return self.test


from datetime import datetime
from spython.main.parse.recipe import Recipe
from spython.main.parse.writers import SingularityWriter

def compose_platform_recipe(
    base_image: str,
    installables: list[Installable] | None = None,
    env_vars: dict[str, str] | None = None,
    dnf_update: list[str] = [
        "dnf install -y ca-certificates tar gzip which findutils file shadow-utils",
        "dnf install -y epel-release",
        "mkdir -p /work /tmp/spack-user-config /tmp/spack-user-cache /tmp/spack-misc-cache",
    ],
) -> tuple[Recipe, str]:
    """Build a Singularity definition for the reusable platform image."""

    recipe = Recipe()
    recipe.fromHeader = base_image.replace("docker://", "")
    recipe.test = ["command -v spack"]

    recipe.comments = [
        "This Singularity definition is generated by the RSE Workbench.",
        "It defines the base platform image for reproducible research projects.",
        "Definition created on: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    ]
    
    recipe.install = dnf_update

    for item in installables:
        recipe.install.extend(item.install_lines())
        recipe.test.extend(item.test_lines())

    recipe.environ = [
        "PATH=/usr/local/bin:/opt/views/view/bin:/root/.cargo/bin:/usr/cargo/bin:$PATH",
        "SPACK_DISABLE_LOCAL_CONFIG=true",
        "SPACK_USER_CONFIG_PATH=/tmp/spack-user-config",
        "SPACK_USER_CACHE_PATH=/tmp/spack-user-cache",
        "SPACK_MISC_CACHE_PATH=/tmp/spack-misc-cache",
    ]

    for key, value in (env_vars or {}).items():
        recipe.environ.append(f"{key}={value}")
    
    recipe.workdir = "/work"

    return recipe

def recipe_to_definition(recipe: Recipe) -> str:
    """Convert a Singularity Recipe to a definition string."""
    writer = SingularityWriter({"spython-base": recipe})
    return writer.convert()
